### ISSUE TITLE
Unable to verify gauge field size or precision

### ISSUE THREAD

**Issue by matveevma** [etmc/tmLQCD#430]
Hi!

After reboot my nodes i have error output messages from each thread:

```
...
LIME record with name: "ildg-format", in gauge file .conf.t00009.tmp either missing or malformed.
Unable to verify gauge field size or precision.
...
```

I find this message in [source code](https://github.com/etmc/tmLQCD/blob/master/io/gauge_read.c)

```
    if (!ildgformat_read_flag) {
      fprintf(stderr, "LIME record with name: \"ildg-format\", in gauge file %s either missing or malformed.\n", filename);
      fprintf(stderr, "Unable to verify gauge field size or precision.\n");
      destruct_reader(reader);
      free(ildgformat_input);
      return(-1);
    }
```

What is mean? What i can do for solve this problem? Thanks!

**Comment by kostrzewa** [comment]
Hi, I would say that your files simply got corrupted. In the LIME format, the first couple hundred to couple thousand bytes (depending on the program which wrote the file) of the gauge configuration contain metadata such as the configuration precision, generation parameters or the size of the lattice, for example:

```
Eg<89><AB>^@^A<C0>^@^@^@^@^@^@^@^@<E5>xlf-info^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
 plaquette = 0.540875831712
 trajectory nr = 2
 beta = 1.726000, kappa = 0.140065, mu = 0.003000, c2_rec = -0.331000
 time = 1477033992
 hmcversion = 5.2.0
 mubar = 0.140800
 epsilonbar = 0.152100
 date = Fri Oct 21 09:13:12 2016
^@^@^@Eg<89><AB>^@^A<80>^@^@^@^@^@^@^@^Aqildg-format^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@<?xml 
version="1.0" encoding="UTF-8"?>
<ildgFormat xmlns="http://www.lqcd.org/ildg"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.lqcd.org/ildg/filefmt.xsd">
  <version>1.0</version>
  <field>su3gauge</field>
  <precision>64</precision>
  <lx>32</lx>
  <ly>32</ly>
  <lz>32</lz>
  <lt>64</lt>
</ildgFormat>
```

Are you doing HMC?

Did you check the file size? Did you take a look at the apparently corrupted file using ```less``` or similar? 

If you're doing HMC and the header is absent or if the file size differs, you will need to backtrack to an older configuration and restart from there. You can do this by modifying the (hidden) file ```.nstore_counter``` in the working directory of your HMC run.

If you're just doing inversions, then you will have to skip this gauge configuration.

**Comment by kostrzewa** [comment]
> Are you doing HMC?

I'll answer my own question: since this is a ```.tmp``` file, you're apparently doing HMC and will have to modify ```.nstore_counter```.

The first number is the next configuration index to be saved, the second number is the next trajectory number and the filename at the end is the filename that should be started from. Thus, if you have a file ```conf.0004``` (or so) from which you want start and this file corresponds to trajectory 16, say, you would set ```.nstore_counter``` to

```
5 17 conf.0004
```

and tmLQCD would then start trajectory 17 from ```conf.0004``` and upon the next save interval, ```conf.0005``` would be written. Let me know if this is unclear.

**Comment by mpdeka** [comment]
Hi Martin, actually I am running tmLQCD code at newly installed Govorun cluster at JINR, Dubna since May 28 this year. I was not aware that Mikhail Matveev wrote to you. Since he is not working on Lattice QCD, I decided to step in otherwise certain key things may be missed.
 
  I pretty much sure that the whole issue has nothing to do with tmLQCD code and Lime library. The error messages of Lime library posted here are symptoms of something else. There were some strange changes at the cluster from about a month ago. Till then everything was fine. They downgraded slurm version from 17.16 to 17.02. I don't know how and why they did the downgrade. Additionally, one needs to be very careful in this going backward process. Since then there were several problems including node communication. Slurm has several broken features. Compiler installation is not complete and so on. As you can see from the post, the the Lime header files are corrupted. 

  The Lime error messages are appearing quite randomly. In the chain of generating configurations, sometime all cores report missing or malformed ildg format, sometimes 2 cores, sometimes a few more and so on within the same job. Clearly it is a problem of Filesytem or hardware or both. Since last one month, I have been writing to the SysAdmin that they need to fix their side of problems. 

  At this moment, all the hardware and software issues at the cluster have to be fixed. Till then, to discuss about tmLQCD code which has successfully passed through several tests on several different machines (including in the early phase of Govorun) makes no sense. Lime library is even more widely used without any issue at any cluster around the world.

**Comment by matveevma** [comment]
I am will check it. Thanks!
